### ISSUE TITLE
[ENH] Use las2peer service properties

### ISSUE THREAD

**Issue by pdolif** [lananh03/getWeather#2]
1. **Motivation** - It would be nice to use service properties offered by las2peer for the app id of openweathermap.
2. **Specification**
     - Add property to properties file
     - Add property to main class
     - Use property in API call
3. **Finalised state** - System should use service properties for the openweathermap app id.

**Comment by pdolif** [comment]
The commit https://github.com/lananh03/getWeather/commit/7035b08e7b6a2db1188cae0192dc2110b5520b95 and the following ones solve this issue.

**Comment by lananh03** [comment]
html file [https://github.com/lananh03/getWeather/commit/4cca33f827ecdcb090a7d188c2fb6c0ed12084d1](url)

**Comment by phil-cd** [comment]
html file https://github.com/lananh03/getWeather/commit/4cca33f827ecdcb090a7d188c2fb6c0ed12084d1

**Comment by lananh03** [comment]
html file https://github.com/lananh03/getWeather/commit/4cca33f827ecdcb090a7d188c2fb6c0ed12084d1
